name: Build WPPConnect Mobile

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-1/x64
      RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Decode release keystore
      run: |
        echo "$RELEASE_KEYSTORE_BASE64" | base64 --decode > android/release-key.jks

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install npm dependencies
      run: npm install --legacy-peer-deps

    - name: Build Release APK
      working-directory: android
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=$PWD/release-key.jks \
          -Pandroid.injected.signing.store.password=$RELEASE_KEYSTORE_PASSWORD \
          -Pandroid.injected.signing.key.alias=$RELEASE_KEY_ALIAS \
          -Pandroid.injected.signing.key.password=$RELEASE_KEYSTORE_PASSWORD

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: wppconnect-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
