name: Build WPPConnect Mobile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.8-9/x64

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Ensure npm uses latest version
      - name: Upgrade npm
        run: npm install -g npm@latest

      # Install dependencies safely (resolving peer conflicts)
      - name: Install npm dependencies
        run: npm install --legacy-peer-deps

      # Optional: Fix specific React Native dependency conflict
      - name: Fix React Native SVG version
        run: |
          npm install react-native-svg@14.8.0 --legacy-peer-deps
          npm install react-native-qrcode-svg@6.3.15 --legacy-peer-deps

      # Decode release keystore if secret exists
      - name: Decode release keystore
        if: ${{ secrets.RELEASE_KEYSTORE_BASE64 != '' }}
        run: |
          mkdir -p android
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > android/release-key.jks

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # Build Android release
      - name: Build Android Release
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$PWD/release-key.jks \
            -Pandroid.injected.signing.store.password="${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" \
            -Pandroid.injected.signing.key.alias="${{ secrets.RELEASE_KEY_ALIAS }}" \
            -Pandroid.injected.signing.key.password="${{ secrets.RELEASE_KEY_PASSWORD }}"

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wppconnect-apk
          path: android/app/build/outputs/apk/release/app-release.apk
