name: Build WPPConnect Mobile APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.8-9/x64
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Java 21
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # Restore or install Gradle wrapper permissions
      - name: Ensure Gradle Wrapper Executable
        run: chmod +x ./android/gradlew

      # Use keystore from secret
      - name: Use Keystore from Secret
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > android/release-key.jks

      # Build Release APK
      - name: Build Release APK
        working-directory: android
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$PWD/release-key.jks \
            -Pandroid.injected.signing.store.password=MyStrongPassword123 \
            -Pandroid.injected.signing.key.alias=wppconnectkey \
            -Pandroid.injected.signing.key.password=MyStrongPassword123

      # Upload APK artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wppconnect-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
