name: Build WPPConnect Mobile

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Decode release keystore
      if: ${{ secrets.RELEASE_KEYSTORE_BASE64 != '' }}
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > android/release-key.jks

    - name: Make Gradle wrapper executable
      run: chmod +x ./android/gradlew

    - name: Build Release APK
      working-directory: android
      run: ./gradlew assembleRelease \
        -Pandroid.injected.signing.store.file=$PWD/release-key.jks \
        -Pandroid.injected.signing.store.password="${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" \
        -Pandroid.injected.signing.key.alias="${{ secrets.RELEASE_KEY_ALIAS }}" \
        -Pandroid.injected.signing.key.password="${{ secrets.RELEASE_KEY_PASSWORD }}"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk
