name: Build WPPConnect Mobile

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0

    - name: Decode Keystore
      run: |
        echo "$RELEASE_KEYSTORE_BASE64" | base64 --decode > release-key.jks
      env:
        RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}

    - name: Build Release APK
      run: |
        cd android
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=$PWD/release-key.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.STORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: WPPConnect-APK
        path: android/app/build/outputs/apk/release/app-release.apk
