name: Build WPPConnect Mobile APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 20
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # 3️⃣ Setup Java 21
      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 4️⃣ Install Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2

      # 5️⃣ Decode release keystore
      - name: Decode release keystore
        if: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > android/release-key.jks

      # 6️⃣ Install NPM dependencies
      - name: Install NPM dependencies
        run: npm install --legacy-peer-deps

      # 7️⃣ Upgrade Gradle wrapper to 8.x
      - name: Upgrade Gradle Wrapper
        working-directory: android
        run: ./gradlew wrapper --gradle-version 8.3.3

      # 8️⃣ Make Gradle Wrapper Executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./android/gradlew

      # 9️⃣ Build APK (Release)
      - name: Build Android Release APK
        working-directory: android
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$PWD/release-key.jks \
            -Pandroid.injected.signing.store.password="${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" \
            -Pandroid.injected.signing.key.alias="${{ secrets.RELEASE_KEY_ALIAS }}" \
            -Pandroid.injected.signing.key.password="${{ secrets.RELEASE_KEY_PASSWORD }}"

      # 🔟 Upload APK artifact
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
